######################################################################
# Automatically generated by qmake (2.01a) ?? 15. ??? 22:39:07 2011
######################################################################

QT       += core gui sql
TEMPLATE = app
TARGET = 
DEPENDPATH += . debug src src/comdoc src/uodbmanager
INCLUDEPATH += . src src/comdoc src/uodbmanager

# Input
HEADERS += src/uomainwindow.h \
           src/comdoc/newtabledlg.h \
           src/comdoc/tableformatdlg.h \
           src/comdoc/uoabstractmdichild.h \
           src/comdoc/uocomonmainwnd.h \
           src/comdoc/uolhsettingthdlg.h \
           src/comdoc/uomdiobserver.h \
           src/comdoc/uomditextedit.h \
           src/comdoc/uorichtextedit.h \
           src/comdoc/uotexteditcomplit.h \
           src/uodbmanager/uodbform.h \
           src/uodbmanager/uodbformelement.h \
           src/uodbmanager/uodbguifactory.h \
           src/uodbmanager/uodblineedit.h \
           src/uodbmanager/uodblistform.h \
           src/uodbmanager/uodbmanager.h \
           src/uodbmanager/uodbmanagerdlg.h \
           src/uodbmanager/uodbmodel.h \
           src/uodbmanager/uodbreftableqmodel.h \
           src/uodbmanager/uodbreftableview.h \
           src/uodbmanager/uodbreftreemodel.h \
           src/uodbmanager/uodbtreeform.h \
           src/uodbmanager/uodbtreeview.h \
           src/uodbmanager/uodefines.h \
           src/uodbmanager/uotextedit.h \
           src/uodbmanager/uourl.h \
    src/comdoc/linkproperty.h
FORMS += src/comdoc/newtabledlg.ui \
         src/comdoc/tableformatdlg.ui \
         src/comdoc/uolhsettingthdlg.ui \
         src/uodbmanager/uodbformelement.ui \
         src/uodbmanager/uodblineedit.ui \
         src/uodbmanager/uodblistform.ui \
         src/uodbmanager/uodbtreeform.ui \
    src/comdoc/linkproperty.ui
SOURCES += src/main.cpp \
           src/uomainwindow.cpp \
           src/comdoc/newtabledlg.cpp \
           src/comdoc/tableformatdlg.cpp \
           src/comdoc/uoabstractmdichild.cpp \
           src/comdoc/uocomonmainwnd.cpp \
           src/comdoc/uolhsettingthdlg.cpp \
           src/comdoc/uomdiobserver.cpp \
           src/comdoc/uomditextedit.cpp \
           src/comdoc/uorichtextedit.cpp \
           src/comdoc/uotexteditcomplit.cpp \
           src/uodbmanager/uodbform.cpp \
           src/uodbmanager/uodbformelement.cpp \
           src/uodbmanager/uodbguifactory.cpp \
           src/uodbmanager/uodblineedit.cpp \
           src/uodbmanager/uodblistform.cpp \
           src/uodbmanager/uodbmanager.cpp \
           src/uodbmanager/uodbmanagerdlg.cpp \
           src/uodbmanager/uodbmodel.cpp \
           src/uodbmanager/uodbreftableqmodel.cpp \
           src/uodbmanager/uodbreftableview.cpp \
           src/uodbmanager/uodbreftreemodel.cpp \
           src/uodbmanager/uodbtreeform.cpp \
           src/uodbmanager/uodbtreeview.cpp \
           src/uodbmanager/uotextedit.cpp \
           src/uodbmanager/uourl.cpp \
    src/comdoc/linkproperty.cpp
RESOURCES += src/uomainwindow.qrc \
             src/comdoc/uocommonmdi.qrc \
             src/uodbmanager/uodbmanager.qrc
TRANSLATIONS += uoReceptor_ru.ts



